import Navbar from '@/components/Navbar'
import PageBody from '@/components/PageBody'
import Head from 'next/head'




export default function Home() {
  return (
    <>
      <Head>
        <title>Thomas Mathew Test Slate.com</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
         <Navbar/>
      </header>
      <main>
         <PageBody/>
      </main>
    </>
  )
}
